name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create new release
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.RELEASE_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.RELEASE_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ github.token }}
          git-user-name: ${{ steps.import-gpg.outputs.name }}
          git-user-email: ${{ steps.import-gpg.outputs.email }}
          output-file: "CHANGELOG.md"
          tag-prefix: "v"
          fallback-version: "1.0.0"
          release-count: "0"
          skip-on-empty: true
          skip-version-file: true
          git-message: "docs: update CHANGELOG.md for {version} [skip ci]"
          pre-release: false

      - name: Create GitHub Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          prerelease: false
